### ISSUE TITLE
Issue with isValid()

### ISSUE THREAD

**Issue by Shaneajm** [DoctorMcKay/node-steamid#8]
Hello. I've been trying to set this up for a project and I'm having an issue with the .isValid() method. I'm relatively new to javascript so this could just be something dumb on my part. 

Basically I'm checking to see if a SteamID is valid or not.

![is valid code](https://user-images.githubusercontent.com/9031327/82746065-931f6f00-9d40-11ea-9479-e96e06c96857.png)

My understanding is that if the value is true it'll do 'x' but if the value is false it'll do 'y'. 

However when it's not valid, instead of doing 'y' it throws the invalid steamid error and crashes the app.

![isvalid error](https://user-images.githubusercontent.com/9031327/82746076-b2b69780-9d40-11ea-971e-9644602193f1.png)

Any guidance is appreciated.

**Comment by DoctorMcKay** [comment]
Yes, you're misunderstanding how to check the validity of a SteamID. You can construct a SteamID with a valid format, but an invalid value. For example, `'[U:6:46143802]'` would construct successfully, but `isValid()` would return false because 6 isn't a valid universe.

To check if a user-provided string is a valid individual SteamID, you'd want to do something like this:

```js
try {
    let sid = new SteamID(input);
    if (sid.universe != SteamID.Universe.PUBLIC || sid.type != SteamID.Type.INDIVIDUAL) {
        throw new Error('Invalid universe or SteamID type');
    }
    // SteamID is valid
catch (ex) {
    // SteamID is not valid
}
```
