### ISSUE TITLE
Would you accept a pull request to convert a URL to a steamid?

### ISSUE THREAD

**Issue by Turbine1991** [DoctorMcKay/node-steamid#9]
Hey,
I've had to add a few feature to convert a steam profile URL to steamid. Whether using a steamid64 or name as the profile identifier. (The latter uses the Steam API and would require the user to provide a key, also uses axios)
`http://steamcommunity.com/profiles/76561198050677486`
`http://steamcommunity.com/profiles/madhatter`

I also don't think an incorrect steam id should throw an exception. As people have implemented this library, it's probably too late. But the isValid() function could've been used instead.

**Comment by DoctorMcKay** [comment]
No, I would say that's out of scope for this module.

I get what you're saying about exceptions, but this module is meant to closely mimic the behavior of the CSteamID class in the official SteamWorks libraries. `isValid()` is not meant to tell you whether a SteamID was parsed successfully (which is when the error gets thrown; when the SteamID cannot be parsed). It's meant to tell you whether a given SteamID is considered valid based on its components. For example `[U:6:46143802]` can be parsed as a SteamID since it's formatted like one, but universe 6 is not valid so `isValid()` is false.
